### ISSUE TITLE
Refactor resource API

### ISSUE THREAD

**Issue by avdgrinten** [qword-os/lai#10]
The API to iterate over a ACPI resource buffer (e.g., the buffer returned by `_CRS`) should be implemented as a lightweight (non-allocating) iterator over a buffer (defined by a `const void *` + `size_t`). 

Suggestions for methods:
 - `lai_resource_read()`: advance to the next resource descriptor or determine that no such descriptor exists
- `lai_resource_get_type()`: return the type of the descriptor
- `lai_resource_get_irq()`: take an index `n` and return the `n`-th IRQ vector

**Comment by thomtl** [comment]
Sorry the reference was a typo

**Comment by avdgrinten** [comment]
Let me further elaborate on an idea for the interface:

```c
struct lai_resource_iterator {
    size_t off; // Offset of the current resource inside the buffer.
    size_t i;
    lai_variable_t *var;
};

/* Moves the iterator to the next resource.
 * Returns zero iff there is no next resource. */
int lai_resource_read(struct lai_resource_iterator *iter);

/* Returns the type of the current resource. */
enum lai_resource_type lai_resource_type(struct lai_resource_iterator *it);

/* Returns the IRQ flags. */
int lai_resource_get_irq_flags(struct lai_resource_iterator *it);

/* Returns the next IRQ of the current resource.
 * Returns zero iff there is no next IRQ. */
int lai_resource_get_next_irq(struct lai_resource_iterator *it, int *irq);

/* If only a single IRQ is set for the current resource, return this IRQ. */
int lai_resource_get_unique_irq(struct lai_resource_iterator *it);

// [...] (similar APIs for other resource types)
```

Because `lai_resource_get_next_irq()` can iterate over multiple IRQs, the iterator can be used to iterate over `_PRT` as well.

Example usage:
```c
while (lai_resource_read(&it)) {
    switch (lai_resource_type(&it)) {
        case LAI_RESOURCE_IRQ: {
            int irq;
            while (lai_resource_get_next_irq(&it, &irq))
                printf("device can use IRQ %d\n", irq);
            break;
        }
        // [...]
    }
}
```

Note that I did not really think about error handling while writing the pseudo code above. We should treat the resource buffer as external input and return errors if it has a bad format.

**Comment by thomtl** [comment]
How would we handle if we have reached the final IRQ in a resource, should i just return null or skip until the next interrupt resource.

Also for error handling i thought of something like this
```cpp
lai_api_error_t lai_resource_iterate(struct lai_resource_iterator *iter, struct lai_resource *resource);
```
Where `resource` is used the same as `result` in lai_eval(), so the allocating of the resource would be done by the caller

**Comment by avdgrinten** [comment]
If the last IRQ for the current resource is reached, we should just return 0 and not advance to the next resource.

I do not really see why we need a separate `struct lai_resource` - I would like to keep the interface lightweight as possible.

**Comment by thomtl** [comment]
Maybe we should move the resource struct from acpispec/resources.h to lai/helpers/resources.h, that would keep it simple
