### ISSUE TITLE
Missing opcode: Implement BreakPoint() and Fatal()

### ISSUE THREAD

**Issue by avdgrinten** [qword-os/lai#37]
Add the missing opcode and a unit test.

**Comment by thomtl** [comment]
How should we handle a breakpoint?
I was thinking of creating a laihost_function which will get all the relevant data (Table it occurred in, PC) and give the host a choice of returning or not.

**Comment by qookei** [comment]
Does AML on real hardware even use BreakPoint()? If no, why bother with it?

**Comment by thomtl** [comment]
Its not exactly a very complicated opcode (just itself) and it would be nice to just have it. Also some people might run on Engineering bioses that might have them

**Comment by avdgrinten** [comment]
IMHO we can just warn and ignore BreakPoint().

**Comment by thomtl** [comment]
Alright, i'll have breakpoint up shortly, but fatal has termargs so imma figure that whole thing out

**Comment by avdgrinten** [comment]
Why do you skip 2 bytes after the breakpoint opcode? Did you add a unit test for this?

**Comment by avdgrinten** [comment]
Fatal() can probably be handled as the other AML operators (e.g., Add()).

**Comment by thomtl** [comment]
I did actually create a unit test, but im dumb
