### ISSUE TITLE
PM Timer 

### ISSUE THREAD

**Issue by Itay2805** [qword-os/lai#41]
Adding a PM Timer helper could be a pretty nice and simple addition to Lai.

**Comment by avdgrinten** [comment]
Can you elaborate on that? What features do you want/except from such an API?

**Comment by Itay2805** [comment]
probably something pretty similar to the lai_get_sci_event. nothing too fancy

**Comment by thomtl** [comment]
We talkes about this a bit in #qword, imo it would be better as a small driver that users can choose to compile in. Since the PM timer uses an SCI to deliver its IRQ it should only need these functions really
‘’’cpp
void enable_pm_timer(uint64_t frq);
void disable_pm_timer();
‘’’

**Comment by avdgrinten** [comment]
Yes, something like that can be added as a driver.
