### ISSUE TITLE
lai_acpi_reset() should return lai_api_error_t

### ISSUE THREAD

**Issue by avdgrinten** [qword-os/lai#45]
https://github.com/qword-os/lai/blob/a979904bdae9870b2aef6029bc9673fc1e3de63e/helpers/pm.c#L113
Instead of returning a numerical error code, we should return proper errors.

**Comment by thomtl** [comment]
Should i also do this for `lai_enter_sleep()`?

**Comment by avdgrinten** [comment]
In general, I think every function that can fail should return an `api_error_t` unless there is a specific reason why an int (or a different type) is more appropriate. For example, for `lai_exec_reserve_stack` it makes sense to just return an int, because the only conceivable failure is OOM. Here, however, multiple bad things can happen.

**Comment by thomtl** [comment]
Resolved in d57102f35c5f0d9b63a38b21517db5f1a85a9a9a

**Comment by avdgrinten** [comment]
Thanks for the quick fix. :+1:
